export type ExerciseCategory = "yoga" | "stretching" | "breathing" | "strength" | "dance";
export type Difficulty = "gentle" | "moderate" | "active";
export type Tint = "primary" | "secondary" | "tertiary";

export interface Exercise {
  id: string;
  name: string;
  desc: string;
  category: ExerciseCategory;
  difficulty: Difficulty;
  durationMin: number;
  isSeated: boolean;
  tint: Tint;
  icon: string;
  steps: string[];
  youtubeQuery: string;
}

export const EXERCISES: Exercise[] = [
  {
    id: "chair-yoga",
    name: "Chair Yoga",
    desc: "Gentle seated yoga suitable for all bodies and spaces. No mat needed.",
    category: "yoga",
    difficulty: "gentle",
    durationMin: 15,
    isSeated: true,
    tint: "primary",
    icon: "self_improvement",
    youtubeQuery: "chair yoga for beginners seated gentle 15 minutes",
    steps: [
      "Sit tall with feet flat on the floor, hands resting on your thighs.",
      "Breathe in slowly and raise both arms overhead. Exhale and lower them.",
      "Roll your shoulders back gently 5 times, then forward 5 times.",
      "Drop your right ear toward your right shoulder. Hold 3 slow breaths. Repeat left.",
      "Place your left hand on your right knee and gently twist to the right. Hold 3 breaths.",
      "Repeat the twist to the left side.",
      "Extend one leg at a time, pointing and flexing the foot 5 times each.",
      "Close with 3 deep belly breaths, hands on your heart.",
    ],
  },
  {
    id: "morning-yoga",
    name: "Morning Yoga Flow",
    desc: "A gentle wake-up sequence to ease into the day with grace.",
    category: "yoga",
    difficulty: "gentle",
    durationMin: 10,
    isSeated: false,
    tint: "primary",
    icon: "wb_sunny",
    youtubeQuery: "morning yoga for beginners 10 minutes gentle wake up",
    steps: [
      "Stand tall or sit comfortably. Take 3 deep breaths to arrive in your body.",
      "Slowly roll your neck in a gentle half-circle, side to side.",
      "Reach both arms up, interlace fingers and stretch upward. Hold 5 breaths.",
      "Forward fold gently — let your upper body hang heavy. Bend knees if needed.",
      "Come to a comfortable seat. Twist gently right, then left.",
      "End in stillness: hands on heart, one hand on belly. Feel yourself breathing.",
    ],
  },
  {
    id: "restorative-yoga",
    name: "Restorative Yoga",
    desc: "Deep rest and release. Perfect for difficult days when rest is needed most.",
    category: "yoga",
    difficulty: "gentle",
    durationMin: 20,
    isSeated: true,
    tint: "primary",
    icon: "spa",
    youtubeQuery: "restorative yoga 20 minutes for stress relief beginners",
    steps: [
      "Find a comfortable position — seated, lying down, or supported by pillows.",
      "Close your eyes and simply breathe. Notice the breath without changing it.",
      "Gently press your shoulder blades together. Hold, then release.",
      "Tense your hands into fists, then open them wide. Repeat 3 times.",
      "Take a long exhale, making a gentle 'haaa' sound. Let tension leave.",
      "Rest in stillness for as long as feels right. You deserve this pause.",
    ],
  },
  {
    id: "full-body-stretch",
    name: "Full Body Stretch",
    desc: "Release tension from head to toe with this calming stretch sequence.",
    category: "stretching",
    difficulty: "gentle",
    durationMin: 10,
    isSeated: false,
    tint: "secondary",
    icon: "accessibility_new",
    youtubeQuery: "full body stretch 10 minutes gentle beginner tension release",
    steps: [
      "Stand or sit. Interlace your fingers and stretch your arms up tall. Hold 5 breaths.",
      "Side stretch: lean gently to the right, then left. Feel the ribs opening.",
      "Bring one arm across your chest, hold with the other arm. Stretch 20 seconds each side.",
      "Reach one arm overhead and bend at the elbow. Gently push the elbow back. Each side.",
      "Seated: extend your legs and reach toward your toes as far as is comfortable.",
      "Gentle ankle circles — 5 times each direction on each foot.",
      "End with a big full-body stretch: arms up, yawn if you'd like!",
    ],
  },
  {
    id: "neck-shoulder",
    name: "Neck & Shoulder Release",
    desc: "Quick relief for tension held in the neck and shoulders. Seated, 5 minutes.",
    category: "stretching",
    difficulty: "gentle",
    durationMin: 5,
    isSeated: true,
    tint: "secondary",
    icon: "airline_seat_recline_normal",
    youtubeQuery: "neck shoulder stretch release seated 5 minutes tension headache",
    steps: [
      "Sit tall. Drop your chin to your chest. Hold 5 breaths.",
      "Slowly look up toward the ceiling. Hold 5 breaths.",
      "Right ear to right shoulder. Left hand lightly rests on your head (no pulling). 5 breaths.",
      "Left ear to left shoulder. 5 breaths.",
      "Roll your shoulders: up, back, down. Repeat 5 times, then reverse.",
      "Squeeze your shoulders up to your ears, hold 3 seconds, then drop them. Repeat 3 times.",
    ],
  },
  {
    id: "hip-opener",
    name: "Hip Opening Sequence",
    desc: "Release deep-held tension in the hips — where we often store stress.",
    category: "stretching",
    difficulty: "moderate",
    durationMin: 10,
    isSeated: false,
    tint: "secondary",
    icon: "fitness_center",
    youtubeQuery: "hip opener stretch for beginners 10 minutes stress relief",
    steps: [
      "Stand with feet wider than hips. Slowly lower into a comfortable squat if possible.",
      "Or: sit in a chair and cross your right ankle over your left knee (figure-4 shape).",
      "Gently press the right knee down. Breathe into the hip for 5-10 breaths.",
      "Switch sides: left ankle over right knee.",
      "Seated: draw your knee toward your opposite shoulder. Hold each side.",
      "Finish with gentle hip circles — imagine stirring a big pot with your hips.",
    ],
  },
  {
    id: "box-breathing",
    name: "Box Breathing",
    desc: "A Navy-proven technique to calm the nervous system in minutes.",
    category: "breathing",
    difficulty: "gentle",
    durationMin: 5,
    isSeated: true,
    tint: "primary",
    icon: "crop_square",
    youtubeQuery: "box breathing technique guided 5 minutes anxiety calm",
    steps: [
      "Sit comfortably. Exhale completely through your mouth.",
      "Breathe IN through your nose for 4 counts. (1-2-3-4)",
      "HOLD your breath for 4 counts. (1-2-3-4)",
      "Breathe OUT through your mouth for 4 counts. (1-2-3-4)",
      "HOLD empty for 4 counts. (1-2-3-4)",
      "Repeat this box pattern 4-6 times.",
      "Notice how your body feels calmer with each cycle.",
    ],
  },
  {
    id: "478-breathing",
    name: "4-7-8 Breathing",
    desc: "A calming breath pattern to reduce anxiety and support sleep.",
    category: "breathing",
    difficulty: "gentle",
    durationMin: 5,
    isSeated: true,
    tint: "primary",
    icon: "air",
    youtubeQuery: "4 7 8 breathing technique guided anxiety sleep calm",
    steps: [
      "Place the tip of your tongue behind your upper front teeth.",
      "Exhale completely through your mouth with a 'whoosh' sound.",
      "Close your mouth. Inhale through your nose for 4 counts.",
      "Hold your breath for 7 counts.",
      "Exhale through your mouth making a 'whoosh' for 8 counts.",
      "That is one full breath. Repeat 3 more times.",
      "Do this twice daily or whenever you feel anxious.",
    ],
  },
  {
    id: "belly-breathing",
    name: "Belly Breathing",
    desc: "Deep diaphragmatic breathing to activate the body's natural calm response.",
    category: "breathing",
    difficulty: "gentle",
    durationMin: 5,
    isSeated: true,
    tint: "primary",
    icon: "psychology",
    youtubeQuery: "belly breathing diaphragmatic breathing guided beginner stress",
    steps: [
      "Place one hand on your chest and one hand on your belly.",
      "Breathe in slowly through your nose. Let your belly push your hand out.",
      "Your chest should move very little. All breath goes into your belly.",
      "Breathe out through pursed lips (like you're blowing through a straw).",
      "Feel your belly fall as you exhale completely.",
      "Continue for 5-10 breaths at a comfortable pace.",
      "Notice any tension melting with each exhale.",
    ],
  },
  {
    id: "seated-core",
    name: "Seated Core Strengthening",
    desc: "Build gentle strength in your core without getting on the floor.",
    category: "strength",
    difficulty: "gentle",
    durationMin: 10,
    isSeated: true,
    tint: "secondary",
    icon: "sports_gymnastics",
    youtubeQuery: "seated core exercises beginners chair gentle strengthening",
    steps: [
      "Sit at the edge of your chair, back straight, hands on the armrests.",
      "Tighten your belly muscles gently (like you expect a soft punch).",
      "Slowly lift one knee toward your chest. Lower it. Alternate 10 times each side.",
      "With both feet on the floor, lean slightly back from the hips. Hold 5 seconds. Return.",
      "March in place: alternating knees, keeping your back straight. 20 marches.",
      "Side bends: slide one hand down the side of your leg toward your knee. Alternate 10 times.",
      "End by sitting tall and taking 5 deep breaths.",
    ],
  },
  {
    id: "wall-exercises",
    name: "Gentle Wall Exercises",
    desc: "Use a wall for support in this accessible strength-building routine.",
    category: "strength",
    difficulty: "moderate",
    durationMin: 10,
    isSeated: false,
    tint: "secondary",
    icon: "fitbit",
    youtubeQuery: "wall exercises gentle strength beginners standing no equipment",
    steps: [
      "Stand about arm's length from a wall, feet shoulder-width apart.",
      "Wall push-up: place palms flat on the wall. Bend elbows and lean in, push back. 10 reps.",
      "Wall squat: back against the wall, slowly slide down to a seated position. Hold 10 seconds.",
      "Single-leg stand: hold wall for balance, lift one foot slightly off the floor. 10 seconds each.",
      "Calf raises: hold wall, rise onto your toes slowly. Lower slowly. 15 reps.",
      "Rest. Shake out your legs gently.",
    ],
  },
  {
    id: "gentle-sway",
    name: "Gentle Sway",
    desc: "Free, gentle movement to reconnect with your body and lift your spirits.",
    category: "dance",
    difficulty: "gentle",
    durationMin: 5,
    isSeated: false,
    tint: "tertiary",
    icon: "music_note",
    youtubeQuery: "gentle free movement dance mindful body awareness calm",
    steps: [
      "Stand comfortably. Close your eyes if it feels safe.",
      "Begin to sway gently side to side, like a tree in a soft breeze.",
      "Let your arms follow naturally — no right or wrong movement.",
      "If music feels good, turn on something you enjoy. Let it move you.",
      "Notice how your body wants to move. Follow that impulse.",
      "This is your time. Move in whatever way brings you ease.",
    ],
  },
  {
    id: "joy-dance",
    name: "Joy Movement",
    desc: "A playful burst of movement to release stuck energy and invite joy.",
    category: "dance",
    difficulty: "moderate",
    durationMin: 10,
    isSeated: false,
    tint: "tertiary",
    icon: "celebration",
    youtubeQuery: "easy dance workout beginner fun gentle uplifting movement",
    steps: [
      "Put on a song that you love or that makes you feel something.",
      "Start by just bobbing your head. Let the music in.",
      "Let your shoulders join. Soft shoulder rolls to the beat.",
      "Let your hips start to move. Side to side, forward and back.",
      "Wave your arms. Reach up, reach out — no rules.",
      "If you want to jump, spin, or stomp — go for it!",
      "End by slowing down gradually with the music, hands on heart.",
    ],
  },
];

export const CATEGORIES: { id: ExerciseCategory | "all"; labelKey: string; icon: string }[] = [
  { id: "all", labelKey: "body.filterAll", icon: "apps" },
  { id: "yoga", labelKey: "body.filterYoga", icon: "self_improvement" },
  { id: "stretching", labelKey: "body.filterStretching", icon: "accessibility_new" },
  { id: "breathing", labelKey: "body.filterBreathing", icon: "air" },
  { id: "strength", labelKey: "body.filterStrength", icon: "fitness_center" },
  { id: "dance", labelKey: "body.filterDance", icon: "music_note" },
];

export const TINT_CLASSES: Record<Tint, { card: string; icon: string; badge: string; btn: string }> = {
  primary: {
    card: "bg-primary-container/20 border-primary-fixed-dim/50",
    icon: "bg-primary-container text-primary",
    badge: "bg-primary-fixed text-on-primary-fixed font-bold",
    btn: "bg-primary text-on-primary",
  },
  secondary: {
    card: "bg-secondary-container/20 border-secondary-fixed-dim/50",
    icon: "bg-secondary-container text-secondary",
    badge: "bg-secondary-fixed text-on-secondary-fixed font-bold",
    btn: "bg-secondary text-on-secondary",
  },
  tertiary: {
    card: "bg-tertiary-container/20 border-tertiary-fixed-dim/50",
    icon: "bg-tertiary-container text-tertiary",
    badge: "bg-tertiary-fixed text-on-tertiary-fixed font-bold",
    btn: "bg-tertiary text-on-tertiary",
  },
};
