import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#fffcf7",
        "on-background": "#383833",
        "surface": "#fffcf7",
        "surface-dim": "#e4e3da",
        "surface-bright": "#fffcf7",
        "surface-variant": "#eae8e0",
        "surface-tint": "#52695e",
        "surface-container": "#f6f3ec",
        "surface-container-low": "#fcf9f3",
        "surface-container-high": "#f0eee6",
        "surface-container-highest": "#eae8e0",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#383833",
        "on-surface-variant": "#65655e",
        "inverse-surface": "#0e0e0c",
        "inverse-on-surface": "#9e9d98",
        "primary": "#52695e",
        "primary-dim": "#465d52",
        "primary-fixed": "#cee9da",
        "primary-fixed-dim": "#c0dacc",
        "primary-container": "#cee9da",
        "on-primary": "#ffffff",
        "on-primary-container": "#40574c",
        "on-primary-fixed": "#2d443a",
        "on-primary-fixed-variant": "#496155",
        "inverse-primary": "#e2fdee",
        "secondary": "#6d6258",
        "secondary-dim": "#61564c",
        "secondary-fixed": "#efe0d2",
        "secondary-fixed-dim": "#e1d2c5",
        "secondary-container": "#efe0d2",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5a5046",
        "on-secondary-fixed": "#473e34",
        "on-secondary-fixed-variant": "#645a4f",
        "tertiary": "#6b6077",
        "tertiary-dim": "#5e546b",
        "tertiary-fixed": "#eee0fc",
        "tertiary-fixed-dim": "#e0d2ed",
        "tertiary-container": "#eee0fc",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#594f66",
        "on-tertiary-fixed": "#463d53",
        "on-tertiary-fixed-variant": "#635970",
        "outline": "#81817a",
        "outline-variant": "#bbb9b2",
        "error": "#af3d3b",
        "error-dim": "#67040d",
        "error-container": "#fa746f",
        "on-error": "#ffffff",
        "on-error-container": "#6e0a12",
      },
      fontFamily: {
        headline: ["'Noto Serif'", "Georgia", "serif"],
        body: ["'Manrope'", "system-ui", "sans-serif"],
        label: ["'Manrope'", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
